# Generated by Django 3.1.2 on 2020-10-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
