# Generated by Django 3.1.2 on 2020-10-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pw', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
